### ISSUE TITLE
Title cannot be inferred from Markdown with Documenter

### ISSUE THREAD

**Issue by theogf** [rikhuijzer/PlutoStaticHTML.jl#112]
In `Documenter.jl` the title of a page can be inferred from the first header. However, when converting a notebook due to the HTML structure the inferred title is just `-`. Would there be a way to solve that? Here is a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/11480067/168575709-cd247bb8-21c0-489f-af4b-65947d519d97.png)

**Comment by rikhuijzer** [comment]
It does work, see for example [TuringGLM.jl](https://beta.turing.ml/TuringGLM.jl/dev/tutorials/linear_regression/). Make sure that you pass pairs to `pages` like
```julia
pages = ["Home" => "index.md", "Tutorials" => ["Max" => "max.md", "Min" => "min.md"]
makedocs(...; pages, ...)
```

Does that solve your issue?

**Comment by theogf** [comment]
Not really :sweat_smile: 

What I meant was that if I have a folder full of notebooks and do not necessarily have names for each of them so writing pairs is not really an option.
Using documenter, if I passed a file `my_example.md` :
```
# Title1

...content

```
as a `String` and not `Pair{String,String}` it would automatically give it the title `Title1`.

**Comment by rikhuijzer** [comment]
That's unfortunate. Still, I think an important part of software development is to say no. In this case, I'm gonna say no because I don't see a way in which this can be elegantly handled at the `PlutoStaticHTML` side. In the worst-case, the `PlutoStaticHTML` logic would differ from the `Documenter` logic which causes things to behave unexpectedly. Taking in `Documenter` as a dependency also seems too heavy-handed because many use-cases of this package don't use the `Documenter` output. Also, I would like to avoid `Requires`.

What I do like about passing pairs of "title => filename" is that it is very explicit. For example, what we did is to define our notebook titles as, for example, ["Foo", "Bar and baz"] and generate the filenames from that as ["foo", "bar-and-baz"].

I'm gonna close for now. Feel free to change my mind and/or reopen.

**Comment by theogf** [comment]
Thanks for the answer! I also thought this could actually be solved on the Documenter side! I fully understand that this is not a priority for you!
