### ISSUE TITLE
Can you use this for automatically downloading and building from a url?

### ISSUE THREAD

**Issue by Dale-Black** [rikhuijzer/PlutoStaticHTML.jl#167]
Given an example url (`"https://github.com/Dale-Black/CalciumScoring.jl/blob/master/src/agatston.jl"`) is there a way to use this package in a Julia script to download and export a static HTML file?

**Comment by rikhuijzer** [comment]
Yes probably. I see that the notebook is not stand-alone because it depends on the directory above it via `Pkg.activate(..)`. Then, the steps will be something like the following:

1. Git clone the repository at https://github.com/Dale-Black/CalciumScoring.jl/
2. `dir = joinpath(repo_dir, "src")`
3. `build_notebooks(BuildOptions(dir), ["agatston.jl"])`

Make sure that opening the Pluto notebook stand-alone works before trying it via `PlutoStaticHtml`. It looks like it wouldn't because the notebook doesn't do `Pkg.instantiate`.
