### ISSUE TITLE
Static Markdown?

### ISSUE THREAD

**Issue by kellertuer** [rikhuijzer/PlutoStaticHTML.jl#19]
Yes this would not fit the name of the package, but how hard would a static markdown export be? I feel like that might be more fitting to the Documenter rendering overall?
Currently I might have to tweak the code cells still I think , since input and output cells look completely the same (I till try to tweak the css soon).

**Comment by rikhuijzer** [comment]
Good question. I've thought about it and I don't think that it is something that I would like to add to this package. The reason is that Markdown is much more limited in its syntax than HTML. With HTML, I'm thinking about adding extra annotations like figure names et cetera via HTML comments and then process them. This wouldn't be possible with Markdown. Another problem is that Markdown has many different flavors whereas HTML is clearly specified.

**Comment by kellertuer** [comment]
Yes and the package name limits this to HTML for sure. It would just maybe be more consistent to produce md-files for processing with documenter.

**Comment by rikhuijzer** [comment]
Yes with Documenter.jl, using the `@raw html` block is indeed a bit of a hack. For Franklin.jl it works really neat though thanks to `utils.jl` and the `~~~` blocks.
