### ISSUE TITLE
Add example of CI for the parallel build

### ISSUE THREAD

**Issue by alecloudenback** [rikhuijzer/PlutoStaticHTML.jl#41]
In the instructions describing how to do the parallel build, it would be nice to reference a complete example of a CI script with the parallel build turned on.

**Comment by rikhuijzer** [comment]
Yes, you are very right! The documentation can still be improved. For now, there is an example implementation at <https://gitlab.com/rikh/blog/-/blob/main/.gitlab-ci.yml>:

```
- julia --project -e 'using Blog; build_notebooks()'
- julia --project -e 'using Franklin; optimize(; minify=false, prerender=false)'
```

where `build_notebooks` is defined as:

```julia
function build_notebooks()
    dir = joinpath("posts", "notebooks")
    append_build_context = true
    bopts = BuildOptions(dir)
    hopts = HTMLOptions(; append_build_context)
    parallel_build(bopts, hopts)
    return nothing
end
```

I've removed the caching from this code to make it easier to read. So, in essence, the `build_notebooks` call generates a lot of HTML files inside `posts/notebooks` and inside Franklin I read those HTML outputs. That way, Franklin has only very little to do and is very quick.

I see that you're building notebooks on a GitHub Runner. Those have only 2 threads available, so the parallel build only halves the running time. In case you are pretty sure that your notebooks don't override methods or set global variables, you can also decide to run PlutoStaticHTML in the `use_distributed=false` mode. In that mode, all notebooks are evaluated inside the same process which avoids having to compile everything from scratch. So, the default `use_distributed=true` is the safest and `use_distributed=false` may be more quick.

I hope this is enough information for you now to be able to continue :) Otherwise, feel free to ping me here or in your PR with specific questions

**Comment by rikhuijzer** [comment]
My plan is to implement something like #49 for Documenter.jl and update the logic in `docs/make.jl` in this repository accordingly. Then, that would be an easy to read example.

**Comment by rikhuijzer** [comment]
There are now many examples for parallel building such as

- https://github.com/rikhuijzer/JuliaTutorialsTemplate
- https://github.com/TuringLang/TuringGLM.jl
- https://github.com/rikhuijzer/Resample.jl
- docs/make.jl in this repository

Some of these are linked in the docs. Hopefully, these examples are clear enough. If not, please re open this issue
