### ISSUE TITLE
Admonitions are poorly formatted in documenter_output

### ISSUE THREAD

**Issue by sethaxen** [rikhuijzer/PlutoStaticHTML.jl#89]
I have the following admonition:

```
!!! note
    
    This tutorial is adapted from [ArviZ's quickstart](https://arviz-devs.github.io/arviz/getting_started/Introduction.html).
```

In Documenter, this looks like:
![image](https://user-images.githubusercontent.com/8673634/159140069-d5a3d52d-b2ab-465b-adfd-845000afdbe7.png)

In Pluto, this looks like:
![image](https://user-images.githubusercontent.com/8673634/159140079-4fe1f423-cead-487c-9226-1609c69b16b3.png)

When building the notebook with PlutoStaticHTML with `documenter_output`, I would have expected it to look like one of the above, but instead it looks like:
![image](https://user-images.githubusercontent.com/8673634/159140113-77489b3a-44b6-4bd8-882e-c83200695524.png)

**Comment by rikhuijzer** [comment]
This is a CSS problem. I try to not add too much CSS because that would make things a lot less flexible on your side. I think you can fix this pretty quickly by adding a bit of CSS styling to your Documenter settings. Having said that, I do agree with you that it makes sense to add some defaults for this kind of stuff. I'll keep this issue open and probably fix it at a later point
