### ISSUE TITLE
Page misformatted when using cached file

### ISSUE THREAD

**Issue by sethaxen** [rikhuijzer/PlutoStaticHTML.jl#90]
When building a notebook for use with Documenter and using a cache, I find that the built notebook renders correctly when the notebook is empty (see https://sethaxen.github.io/PlutoStaticHTMLDemo.jl/dev/notebook/), but upon building the docs again, where the previously built notebook is now in the cache, the resulting docs page instead renders as:
![image](https://user-images.githubusercontent.com/8673634/159144166-3b05051a-af5d-494c-a238-c1adc899fe69.png)

For the execution of `build_notebooks`, see https://github.com/sethaxen/PlutoStaticHTMLDemo.jl/blob/main/docs/make.jl. Have I used `previous_dir` correctly?

**Comment by rikhuijzer** [comment]
I didn't add a test for `documenter_output` in https://github.com/rikhuijzer/PlutoStaticHTML.jl/pull/71 because I thought "why would you want cache anyway in Documenter?". I should fix that test. Anyway, are you sure that you want caching in your case? If you link your documentation to your package which is under development like we did at, for example, [TuringGLM.jl](https://github.com/TuringLang/TuringGLM.jl) then you don't want caching to avoid showing outdated information.

> Have I used `previous_dir` correctly?

I looks like it yes

**Comment by sethaxen** [comment]
Thanks! Honestly, I'm just using this to speed up local development of the rest of the docs, since the notebook is by far the most expensive part to build. The cache is empty when building on CI.

**Comment by rikhuijzer** [comment]
Nice! I have set `DISABLE_NOTEBOOKS_BUILD` in systems ENV and check that variable before building, but I like your solution too
